# Generated by Django 5.1.7 on 2025-03-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Fan nomi')),
                ('grade', models.PositiveIntegerField(verbose_name='Sinf')),
                ('file', models.FileField(upload_to='textbooks/', verbose_name='Darslik fayli')),
                ('language', models.CharField(choices=[('uz', 'O‘zbek'), ('ru', 'Rus'), ('en', 'Ingliz')], max_length=50, verbose_name='Til')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
